version: "3.8"
services:
  scadaplayer:
    image: "killruana/scadaplayer:main"
    ports:
      - 8004:80
    networks:
      - "traefik_public"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.scadaplayer-compress.compress=true"
      - "traefik.http.routers.scadaplayer.entrypoints=websecure"
      - "traefik.http.routers.scadaplayer.middlewares=scadaplayer-compress"
      - "traefik.http.routers.scadaplayer.rule=Host(`scadaplayer.jtremesay.org`, `scadaplayer.slaanesh.org`)"
      - "traefik.http.routers.scadaplayer.service=scadaplayer"
      - "traefik.http.routers.scadaplayer.tls.certresolver=zerossl"
      - "traefik.http.services.scadaplayer.loadbalancer.server.port=80"

networks:
  traefik_public:
    external: true
